DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2FzQGx1Y2FzLmNvbSIsImV4cCI6MTc3ODExNTIwMCwidXNlcklkIjoyfQ.wDVnC2smLt4rc1n2lEkjThl1bMDM9FIH4CGSscbtAio