POST http://localhost:8080/events
content-type: application/json
authorization: 

{
    "name": "Test 33 Event do Lucas 321U7329183291",
    "description": "Description test event",
    "location" : "Event test location",
    "dateTime": "2026-01-01T15:30:00.000Z"
}
