DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2FzMkBsdWNhczIuY29tIiwiZXhwIjoxNzc4MDMxMjAxLCJ1c2VySWQiOjJ9.qnBTvRvapqDIvh6qG-mGEZdYaq4wowQvHTq1IIlynLk